"""add_enrichment_mode_to_items

Revision ID: 2faeb1beb78b
Revises: 006_job_dispatch_listen_notify
Create Date: 2025-12-29 16:14:47.229569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faeb1beb78b'
down_revision: Union[str, None] = '006_job_dispatch_listen_notify'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_outbox_item_id'), table_name='enrichment_outbox', if_exists=True)
    op.drop_index(op.f('idx_idempotency_user_key'), table_name='idempotency_keys', if_exists=True)
    op.create_unique_constraint('uq_idempotency_user_key', 'idempotency_keys', ['user_id', 'idempotency_key'])
    
    # Add enrichment_mode column - first add as nullable
    op.add_column('items', sa.Column('enrichment_mode', sa.String(length=10), nullable=True))
    
    # Update existing rows to have default value 'AI'
    op.execute("UPDATE items SET enrichment_mode = 'AI' WHERE enrichment_mode IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('items', 'enrichment_mode', nullable=False)
    
    op.drop_index(op.f('idx_items_raw_text_trgm'), table_name='items', postgresql_ops={'raw_text': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('idx_items_summary_trgm'), table_name='items', postgresql_ops={'summary': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('idx_items_title_trgm'), table_name='items', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('idx_items_user_id'), table_name='items', if_exists=True)
    op.create_index('idx_items_user_archived', 'items', ['user_id', 'confirmed_at'], unique=False, postgresql_where="status = 'ARCHIVED'", if_not_exists=True)
    op.create_index('idx_items_user_pending', 'items', ['user_id', 'created_at'], unique=False, postgresql_where="status IN ('ENRICHING', 'READY_TO_CONFIRM', 'FAILED')", if_not_exists=True)
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_index('idx_items_user_pending', table_name='items', postgresql_where="status IN ('ENRICHING', 'READY_TO_CONFIRM', 'FAILED')")
    op.drop_index('idx_items_user_archived', table_name='items', postgresql_where="status = 'ARCHIVED'")
    op.create_index(op.f('idx_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_index(op.f('idx_items_title_trgm'), 'items', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_items_summary_trgm'), 'items', ['summary'], unique=False, postgresql_ops={'summary': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_items_raw_text_trgm'), 'items', ['raw_text'], unique=False, postgresql_ops={'raw_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('items', 'enrichment_mode')
    op.drop_constraint('uq_idempotency_user_key', 'idempotency_keys', type_='unique')
    op.create_index(op.f('idx_idempotency_user_key'), 'idempotency_keys', ['user_id', 'idempotency_key'], unique=True)
    op.create_index(op.f('idx_outbox_item_id'), 'enrichment_outbox', ['item_id'], unique=False)
    # ### end Alembic commands ###
