"""add_uploads_and_item_attachments

Revision ID: 3b9894917ca2
Revises: f11ba5bc6cb2
Create Date: 2026-01-05 13:24:22.099869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9894917ca2'
down_revision: Union[str, None] = 'f11ba5bc6cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=100), nullable=True),
    sa.Column('etag', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index('idx_uploads_expires', 'uploads', ['expires_at'], unique=False, postgresql_where="status = 'INITIATED'")
    op.create_index('idx_uploads_idempotency', 'uploads', ['user_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL AND deleted_at IS NULL')
    op.create_index('idx_uploads_user_created', 'uploads', ['user_id', 'created_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('item_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index('idx_attachments_item', 'item_attachments', ['item_id', 'sort_order'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_attachments_user', 'item_attachments', ['user_id', 'created_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_item_attachments_item_id'), 'item_attachments', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_attachments_user_id'), 'item_attachments', ['user_id'], unique=False)
    op.drop_index(op.f('idx_suggestions_item'), table_name='item_tag_suggestions')
    op.create_index(op.f('ix_item_tag_suggestions_item_id'), 'item_tag_suggestions', ['item_id'], unique=False)
    op.drop_index(op.f('idx_item_tags_tag_id'), table_name='item_tags')
    op.drop_index(op.f('idx_tags_user_active'), table_name='tags', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_tags_user_lastused_desc_active'), table_name='tags', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_tags_user_name_asc_active'), table_name='tags', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_tags_user_usage_desc_active'), table_name='tags', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tags_user_usage_desc_active'), 'tags', ['user_id', sa.literal_column('usage_count DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_tags_user_name_asc_active'), 'tags', ['user_id', 'name'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_tags_user_lastused_desc_active'), 'tags', ['user_id', sa.literal_column('last_used DESC NULLS LAST')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_tags_user_active'), 'tags', ['user_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_item_tags_tag_id'), 'item_tags', ['tag_id'], unique=False)
    op.drop_index(op.f('ix_item_tag_suggestions_item_id'), table_name='item_tag_suggestions')
    op.create_index(op.f('idx_suggestions_item'), 'item_tag_suggestions', ['item_id'], unique=False)
    op.drop_index(op.f('ix_item_attachments_user_id'), table_name='item_attachments')
    op.drop_index(op.f('ix_item_attachments_item_id'), table_name='item_attachments')
    op.drop_index('idx_attachments_user', table_name='item_attachments', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_attachments_item', table_name='item_attachments', postgresql_where='deleted_at IS NULL')
    op.drop_table('item_attachments')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index('idx_uploads_user_created', table_name='uploads', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_uploads_idempotency', table_name='uploads', postgresql_where='idempotency_key IS NOT NULL AND deleted_at IS NULL')
    op.drop_index('idx_uploads_expires', table_name='uploads', postgresql_where="status = 'INITIATED'")
    op.drop_table('uploads')
    # ### end Alembic commands ###
