"""add_ai_usage_tables

Revision ID: f11ba5bc6cb2
Revises: 010_add_item_tag_suggestions
Create Date: 2025-12-30 14:17:29.261387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11ba5bc6cb2'
down_revision: Union[str, None] = '010_add_item_tag_suggestions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_daily_usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('enrichment_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('limit_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day_date')
    )
    op.create_table('ai_usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('cost_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_dedup', 'ai_usage_ledger', ['user_id', 'resource_id', 'action'], unique=True)
    op.create_index('idx_ledger_user_date', 'ai_usage_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_ledger_user_id'), 'ai_usage_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_ledger_user_id'), table_name='ai_usage_ledger')
    op.drop_index('idx_ledger_user_date', table_name='ai_usage_ledger')
    op.drop_index('idx_ledger_dedup', table_name='ai_usage_ledger')
    op.drop_table('ai_usage_ledger')
    op.drop_table('ai_daily_usage')
    # ### end Alembic commands ###
